// START_AI_HEADER
// MODULE: bsdos-run/src/jpk.rs
// PURPOSE: Generate a jpk.toml descriptor from an unpacked IPA (Info.plist + entitlements).
// INTENT: Bridge the iOS app world to the bsdOS .jpk package format.  Given the bundle
//         metadata (plist::BundleInfo) and the derived sandbox policy
//         (entitlements::JailPolicy), emit a minimal-but-valid jpk.toml conforming to
//         SPEC_jpk_descriptor_v1 §3 — the same schema that bsdos-pkgd::descriptor::JpkDescriptor
//         parses.  We deliberately do NOT depend on bsdos-pkgd: this crate hand-renders TOML so
//         it stays standalone.  The output is intended to be piped to `bsdos-pkgd inspect/build`.
// DEPENDENCIES: plist::BundleInfo, entitlements::JailPolicy.
// PUBLIC_API: ipa_to_jpk_descriptor.
// END_AI_HEADER

use crate::entitlements::JailPolicy;
use crate::plist::BundleInfo;

/// Schema version emitted; matches SPEC_jpk_descriptor_v1 and bsdos-pkgd validation.
const JPK_SCHEMA_VERSION: &str = "1.0";
/// Default app version when the IPA does not carry a usable semver.
const DEFAULT_VERSION: &str = "0.1.0";

// ipa_to_jpk_descriptor:start
//   purpose: Render a jpk.toml descriptor (TOML text) from bundle metadata + jail policy.
//   input:  bundle — parsed Info.plist metadata; policy — derived JailPolicy (network/audio/gpu).
//   output: String — a TOML document with [meta], [compatibility], [runtime], [permissions]
//           sections, valid against bsdos-pkgd::descriptor::JpkDescriptor.
//   sideEffects: none (pure string construction).
pub fn ipa_to_jpk_descriptor(bundle: &BundleInfo, policy: &JailPolicy) -> String {
    // meta.id must be reverse-DNS lowercase (bsdos-pkgd validate_app_id); sanitise the
    // bundle identifier defensively. iOS identifiers are already reverse-DNS but may contain
    // characters or case the bsdOS validator rejects.
    let app_id = sanitise_app_id(&bundle.bundle_identifier);

    // Arch list: bsdOS Squirrel is multi-arch (aarch64 + amd64 QEMU dev loop). The arm64
    // device-capability is recorded as a comment hint below rather than narrowing the list,
    // because mldr runs the Mach-O on either arch via the bsdOS runtime layer.
    let arch = "[\"aarch64\", \"amd64\"]";

    // jail_name: derive a short, jail-safe name from the last DNS label of the id.
    let jail_name = derive_jail_name(&app_id);

    let name = bundle.best_name();

    let mut out = String::with_capacity(640);

    // === [meta] ===
    out.push_str("# Generated by bsdos-run from an unpacked IPA (Info.plist + entitlements).\n");
    out.push_str("# Conforms to SPEC_jpk_descriptor_v1 §3.\n\n");
    out.push_str("[meta]\n");
    push_kv_str(&mut out, "schema_version", JPK_SCHEMA_VERSION);
    push_kv_str(&mut out, "id", &app_id);
    push_kv_str(&mut out, "version", DEFAULT_VERSION);
    push_kv_str(&mut out, "name", name);
    push_kv_str(&mut out, "description", &format!("iOS app {name} repackaged for bsdOS"));
    push_kv_str(&mut out, "homepage", "");
    push_kv_str(&mut out, "license", "");
    out.push('\n');

    // === [compatibility] ===
    out.push_str("[compatibility]\n");
    push_kv_str(&mut out, "bsdos_codename_min", "Porcupine");
    push_kv_str(&mut out, "freebsd_min", "15.1");
    out.push_str("arch = ");
    out.push_str(arch);
    out.push('\n');
    out.push('\n');

    // === [runtime] ===
    out.push_str("[runtime]\n");
    push_kv_str(&mut out, "type", "jail");
    push_kv_str(&mut out, "jail_name", &jail_name);
    // entrypoint: mldr loads the Mach-O binary; record the bundle executable name.
    push_kv_str(&mut out, "entrypoint", &bundle.bundle_executable);
    push_kv_bool(&mut out, "needs_wayland", true);
    push_kv_bool(&mut out, "needs_input", true);
    push_kv_bool(&mut out, "needs_gpu", policy.gpu);
    push_kv_bool(&mut out, "needs_audio", policy.audio);
    out.push('\n');

    // === [permissions] ===
    out.push_str("[permissions]\n");
    // Network mapping from the jail policy (inet vs none).
    push_kv_str(&mut out, "network", policy.network.jpk_network());
    push_kv_str(&mut out, "filesystem", "ro");
    out.push('\n');

    out
}
// ipa_to_jpk_descriptor:end

// sanitise_app_id:start
//   purpose: Coerce a bundle identifier into a bsdOS-valid reverse-DNS id (lowercase a-z 0-9 . -).
//   input:  raw — the CFBundleIdentifier string.
//   output: String — sanitised id; guarantees at least one dot (falls back to a bsdos.* prefix).
//   sideEffects: none.
fn sanitise_app_id(raw: &str) -> String {
    let mut s: String = raw
        .chars()
        .map(|c| c.to_ascii_lowercase())
        .map(|c| match c {
            'a'..='z' | '0'..='9' | '.' | '-' => c,
            '_' => '-',
            _ => '-',
        })
        .collect();

    // Collapse leading/trailing separators that would be invalid or ugly.
    s = s.trim_matches(|c| c == '.' || c == '-').to_string();

    if s.is_empty() {
        return "org.bsdos.unknown-ipa".to_string();
    }
    // bsdos-pkgd requires a dot (reverse-DNS). If none, namespace it.
    if !s.contains('.') {
        return format!("org.bsdos.{s}");
    }
    s
}
// sanitise_app_id:end

// derive_jail_name:start
//   purpose: Derive a short jail(8)-safe name from a reverse-DNS app id.
//   input:  app_id — sanitised reverse-DNS id.
//   output: String — last DNS label with non-alphanumerics stripped, prefixed "app";
//           never empty.
//   sideEffects: none.
fn derive_jail_name(app_id: &str) -> String {
    let last = app_id.rsplit('.').next().unwrap_or(app_id);
    let cleaned: String = last
        .chars()
        .filter(|c| c.is_ascii_alphanumeric())
        .collect();
    if cleaned.is_empty() {
        "appIpa".to_string()
    } else {
        format!("app_{cleaned}")
    }
}
// derive_jail_name:end

// push_kv_str:start
//   purpose: Append a `key = "value"` TOML line with the value safely escaped.
//   input:  out — accumulator; key — TOML key; value — raw string value.
//   output: none (appends to out).
//   sideEffects: mutates out.
fn push_kv_str(out: &mut String, key: &str, value: &str) {
    out.push_str(key);
    out.push_str(" = \"");
    out.push_str(&escape_toml_basic(value));
    out.push_str("\"\n");
}
// push_kv_str:end

// push_kv_bool:start
//   purpose: Append a `key = true|false` TOML line.
//   input:  out — accumulator; key — TOML key; value — boolean.
//   output: none (appends to out).
//   sideEffects: mutates out.
fn push_kv_bool(out: &mut String, key: &str, value: bool) {
    out.push_str(key);
    out.push_str(if value { " = true\n" } else { " = false\n" });
}
// push_kv_bool:end

// escape_toml_basic:start
//   purpose: Escape a string for a TOML basic (double-quoted) value.
//   input:  s — raw string.
//   output: String with backslash, double-quote, and control chars escaped.
//   sideEffects: none.
fn escape_toml_basic(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04X}", c as u32)),
            c => out.push(c),
        }
    }
    out
}
// escape_toml_basic:end

#[cfg(test)]
mod tests {
    use super::*;
    use crate::entitlements::{JailNetwork, JailPolicy};

    // helper_bundle:start
    //   purpose: Build a BundleInfo for tests.
    //   input:  id / exec / arm64 flag.
    //   output: BundleInfo.
    //   sideEffects: none.
    fn helper_bundle(id: &str, exec: &str, arm64: bool) -> BundleInfo {
        BundleInfo {
            bundle_identifier: id.to_string(),
            bundle_executable: exec.to_string(),
            bundle_name: "Short".to_string(),
            display_name: "My App".to_string(),
            requires_arm64: arm64,
            minimum_os_version: "13.0".to_string(),
            network_client: false,
            network_server: false,
        }
    }
    // helper_bundle:end

    #[test]
    fn test_descriptor_contains_required_sections() {
        let bundle = helper_bundle("com.example.app", "App", true);
        let policy = JailPolicy { network: JailNetwork::Inherit, audio: false, gpu: false };
        let toml = ipa_to_jpk_descriptor(&bundle, &policy);

        assert!(toml.contains("[meta]"));
        assert!(toml.contains("[compatibility]"));
        assert!(toml.contains("[runtime]"));
        assert!(toml.contains("[permissions]"));
        assert!(toml.contains("schema_version = \"1.0\""));
        assert!(toml.contains("id = \"com.example.app\""));
        assert!(toml.contains("type = \"jail\""));
        assert!(toml.contains("entrypoint = \"App\""));
        // Inherit network → "inet"
        assert!(toml.contains("network = \"inet\""));
        assert!(toml.contains("name = \"My App\""));
    }

    #[test]
    fn test_no_network_maps_to_none() {
        let bundle = helper_bundle("com.example.app", "App", true);
        let policy = JailPolicy { network: JailNetwork::Disable, audio: false, gpu: false };
        let toml = ipa_to_jpk_descriptor(&bundle, &policy);
        assert!(toml.contains("network = \"none\""));
    }

    #[test]
    fn test_gpu_audio_flags_propagate() {
        let bundle = helper_bundle("com.example.app", "App", true);
        let policy = JailPolicy { network: JailNetwork::Disable, audio: true, gpu: true };
        let toml = ipa_to_jpk_descriptor(&bundle, &policy);
        assert!(toml.contains("needs_gpu = true"));
        assert!(toml.contains("needs_audio = true"));
    }

    #[test]
    fn test_sanitise_app_id() {
        assert_eq!(sanitise_app_id("Com.Example.App"), "com.example.app");
        assert_eq!(sanitise_app_id("com_example_app"), "org.bsdos.com-example-app");
        assert_eq!(sanitise_app_id("foo"), "org.bsdos.foo");
        assert_eq!(sanitise_app_id(""), "org.bsdos.unknown-ipa");
        assert_eq!(sanitise_app_id("..."), "org.bsdos.unknown-ipa");
    }

    #[test]
    fn test_derive_jail_name() {
        assert_eq!(derive_jail_name("com.example.app"), "app_app");
        assert_eq!(derive_jail_name("org.bsdos.foo123"), "app_foo123");
        assert_eq!(derive_jail_name("no-dot"), "app_nodot");
    }

    #[test]
    fn test_escape_toml_basic() {
        assert_eq!(escape_toml_basic(r#"a"b\c"#), r#"a\"b\\c"#);
        assert_eq!(escape_toml_basic("line1\nline2"), "line1\\nline2");
    }
}
