#!/bin/sh
. "$(dirname "$0")/_ssh.sh"

echo "=== Rust toolchain in VM ==="
echo ""
echo "rustc version:"
ssh_guest "rustc --version 2>/dev/null || echo 'no rustc installed'"
echo ""
echo "rustup version:"
ssh_guest "rustup --version 2>/dev/null || echo 'no rustup installed'"
echo ""
echo "rustup default toolchain:"
ssh_guest "rustup toolchain list 2>/dev/null || echo 'cannot query toolchains'"
echo ""
echo "cargo +nightly version:"
ssh_guest "cargo +nightly --version 2>/dev/null || echo 'no nightly toolchain installed'"
echo ""
echo "Rust target info:"
ssh_guest "rustc --print sysroot 2>/dev/null || echo 'cannot get sysroot'"
echo ""
echo "=== Build environment checks ==="
echo ""
echo "cargo in PATH:"
ssh_guest "which cargo 2>/dev/null || echo 'cargo not found'"
echo ""
echo "cc (C compiler):"
ssh_guest "which cc 2>/dev/null && cc --version | head -1 || echo 'cc not found'"
echo ""
