#!/bin/sh
set -eu
. "$(dirname "$0")/_ssh.sh"
echo "=== DRM/GPU devices ==="
ssh_guest "ls -la /dev/dri/ 2>/dev/null || echo 'no /dev/dri'"
ssh_guest "ls -la /dev/fb* 2>/dev/null || echo 'no framebuffer'"
echo ""
echo "=== Loaded kernel modules (drm-related) ==="
ssh_root "kldstat 2>/dev/null | grep -iE 'drm|vgfb|virtio_gpu' || echo 'no drm-related modules loaded'"
echo ""
echo "=== All loaded kernel modules ==="
ssh_root "kldstat 2>/dev/null | head -20"
echo ""
echo "=== PCI devices (VGA/GPU) ==="
ssh_root "pciconf -l 2>/dev/null | grep -iE 'vga|gpu|display' || echo 'no vga devices found'"
echo ""
echo "=== dmesg GPU messages (last 20 lines matching gpu/drm) ==="
ssh_root "dmesg 2>/dev/null | grep -iE 'virtio.*gpu|drm|vgfb|vga' | tail -20 || echo 'no gpu messages in dmesg'"
echo ""
echo "=== Framebuffer kernel modules available ==="
ssh_root "find /boot/kernel -name '*fb*' -o -name '*drm*' -o -name '*gpu*' 2>/dev/null || echo 'no fb/drm/gpu modules found'"
echo ""
echo "=== seatd status ==="
ssh_root "service seatd status 2>/dev/null || echo 'seatd not running'"
echo ""
echo "=== seatd socket ==="
ssh_guest "ls -la /var/run/seat* 2>/dev/null || echo 'no seat socket'"
